/var/log/clamav/clamonacc.log {
    daily
    size 10k
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 640 clamav clamav
    sharedscripts

    postrotate
        systemctl kill --signal=SIGUSR1 clamav-daemon.service 2>/dev/null || true
        systemctl kill --signal=SIGUSR1 clamav-clamonacc.service > /dev/null 2>&1 || true
    endscript
}
