/var/log/clamav/clamscan.log {
    daily
    size 10k
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 640 root root
    sharedscripts

    postrotate
        systemctl reload clamav-daemon || true
    endscript
}
