[LegalNotice]
Accepted=true

[Preferences]
WebUI\Port=8080
WebUI\Username={{ADMIN_USER}}
WebUI\LocalHostAuth=false
Downloads\SavePath={{QBIT_SAVE_PATH}}
Downloads\TempPath={{QBIT_SAVE_PATH}}/.tmp
Downloads\TempPathEnabled=true
