#!/bin/bash
: '
Title:          WireGuard Add Peer Script
Description:    Generates a new WireGuard peer and outputs a client config file.
Author:         Joek Lemon
Contributors:
Notes:          Reusable — run anytime to add a new device.
                Usage: sudo bash add-peer.sh <device-name>
'

set -o errexit

if [ "$EUID" -ne 0 ]; then
    echo "❌ This script must be run as root"
    echo "   Usage: sudo bash add-peer.sh <device-name>"
    exit 1
fi

if [ -z "$1" ]; then
    echo "❌ Provide a device name"
    echo "   Usage: sudo bash add-peer.sh <device-name>"
    echo "   Example: sudo bash add-peer.sh laptop"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
PEER_NAME="$1"
WG_CONF="/etc/wireguard/wg0.conf"
CLIENT_DIR="$SRC_DIR/host/wireguard/clients"
CLIENT_CONF="$CLIENT_DIR/${PEER_NAME}.conf"

# Check WireGuard is running
if ! ip link show wg0 > /dev/null 2>&1; then
    echo "❌ WireGuard interface wg0 not found"
    exit 1
fi

# Check for duplicate peer name
if grep -q "# peer:${PEER_NAME}$" "$WG_CONF" 2>/dev/null; then
    echo "❌ Peer '${PEER_NAME}' already exists in $WG_CONF"
    exit 1
fi

echo "🔑 Generating WireGuard peer: ${PEER_NAME}"

# Get server public key
SERVER_PUBLIC_KEY=$(wg show wg0 public-key)
SERVER_PORT=$(grep ListenPort "$WG_CONF" | awk '{print $3}')

# Auto-detect VPS public IP
echo "   Detecting VPS public IP..."
VPS_IP=$(curl --fail --silent --connect-timeout 5 ifconfig.me 2>/dev/null || \
         curl --fail --silent --connect-timeout 5 icanhazip.com 2>/dev/null || \
         curl --fail --silent --connect-timeout 5 api.ipify.org 2>/dev/null)

if [ -z "$VPS_IP" ]; then
    echo "❌ Could not detect VPS public IP"
    echo "   Set it manually in the client config file"
    VPS_IP="<SET_YOUR_VPS_IP>"
fi
echo "   VPS IP: $VPS_IP"

# Count existing peers to assign next IP
PEER_COUNT=$(grep -c '^\[Peer\]' "$WG_CONF" 2>/dev/null || echo "0")
NEXT_OCTET=$(( PEER_COUNT + 2 ))

if [ "$NEXT_OCTET" -gt 254 ]; then
    echo "❌ Too many peers (max 253)"
    exit 1
fi

CLIENT_IP="10.0.0.${NEXT_OCTET}"

# Generate keys
echo "   Generating keypair..."
CLIENT_PRIVATE_KEY=$(wg genkey)
CLIENT_PUBLIC_KEY=$(echo "$CLIENT_PRIVATE_KEY" | wg pubkey)
PRESHARED_KEY=$(wg genpsk)

# Check if NextDNS is installed (listening on 10.0.0.1:53)
if ss -ulnp | grep -q "10.0.0.1:53"; then
    CLIENT_DNS="10.0.0.1"
    echo "   DNS: NextDNS (10.0.0.1)"
else
    CLIENT_DNS="9.9.9.9"
    echo "   DNS: Quad9 fallback (9.9.9.9)"
fi

# Append peer to server config
echo "   Adding peer to $WG_CONF..."
cat >> "$WG_CONF" <<EOF

[Peer] # peer:${PEER_NAME}
PublicKey = $CLIENT_PUBLIC_KEY
PresharedKey = $PRESHARED_KEY
AllowedIPs = ${CLIENT_IP}/32
EOF

# Write client config
mkdir --parents "$CLIENT_DIR"
cat > "$CLIENT_CONF" <<EOF
# WireGuard Client Config
# Device: ${PEER_NAME}
# Generated by lemon-vps

[Interface]
PrivateKey = $CLIENT_PRIVATE_KEY
Address = ${CLIENT_IP}/24
DNS = ${CLIENT_DNS}

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
PresharedKey = ${PRESHARED_KEY}
Endpoint = ${VPS_IP}:${SERVER_PORT}
AllowedIPs = 0.0.0.0/0, ::/0
EOF

chmod 600 "$CLIENT_CONF"

# Apply live (no restart needed)
echo "   Applying configuration..."
wg syncconf wg0 <(wg-quick strip wg0)

echo ""
echo "✅ Peer '${PEER_NAME}' created"
echo ""
echo "   Server peer added to $WG_CONF"
echo "   Client config: $CLIENT_CONF"
echo "   Client IP: ${CLIENT_IP}"
echo ""
echo "   Download the config:"
echo "   scp root@${VPS_IP}:${CLIENT_CONF} ."
echo ""
