#!/bin/bash
: '
Title:          Config Generator Script
Description:    Replaces placeholders in config files with user values.
Author:         Joek Lemon
Contributors:
Notes:          Uses {{PLACEHOLDER}} syntax, sed -i to edit in-place.
'

generate_configs() {
    local src_dir="$1"

    echo "🔧 Configuring files..."

    # Install wireguard-tools for key generation
    echo "   Installing WireGuard tools..."
    if command -v apt > /dev/null 2>&1; then
        apt install --yes --quiet wireguard-tools > /dev/null 2>&1
    elif command -v dnf > /dev/null 2>&1; then
        dnf install --yes wireguard-tools > /dev/null 2>&1
    elif command -v yum > /dev/null 2>&1; then
        yum install --yes wireguard-tools > /dev/null 2>&1
    fi

    # Generate WireGuard keys
    echo "   Generating WireGuard keys..."
    WG_PRIVATE_KEY=$(wg genkey)
    WG_PUBLIC_KEY=$(echo "$WG_PRIVATE_KEY" | wg pubkey)
    WG_PRESHARED_KEY=$(wg genpsk)
    WG_CLIENT_PRIVATE_KEY=$(wg genkey)
    WG_CLIENT_PUBLIC_KEY=$(echo "$WG_CLIENT_PRIVATE_KEY" | wg pubkey)

    # Generate Matrix signing key
    echo "   Generating Matrix signing key..."
    MATRIX_SECRET_KEY=$(openssl rand -hex 32)

    # Generate NTFY auth token
    echo "   Generating NTFY auth token..."
    NTFY_TOKEN=$(openssl rand -hex 32)

    # sed in-place replacement
    sed_fill() {
        sed -i \
            -e "s|{{DOMAIN}}|$DOMAIN|g" \
            -e "s|{{EMAIL}}|$EMAIL|g" \
            -e "s|{{ADMIN_USER}}|$ADMIN_USER|g" \
            -e "s|{{ADMIN_PASS}}|$ADMIN_PASS|g" \
            -e "s|{{SYSTEM_USER}}|$SYSTEM_USER|g" \
            -e "s|{{SYSTEM_USER_HOME}}|$SYSTEM_USER_HOME|g" \
            -e "s|{{SYSTEM_USER_UID}}|$SYSTEM_USER_UID|g" \
            -e "s|{{SYSTEM_USER_GID}}|$SYSTEM_USER_GID|g" \
            -e "s|{{MATRIX_SERVER_NAME}}|$MATRIX_SERVER_NAME|g" \
            -e "s|{{MATRIX_SECRET_KEY}}|$MATRIX_SECRET_KEY|g" \
            -e "s|{{WG_PRIVATE_KEY}}|$WG_PRIVATE_KEY|g" \
            -e "s|{{WG_PUBLIC_KEY}}|$WG_PUBLIC_KEY|g" \
            -e "s|{{WG_PRESHARED_KEY}}|$WG_PRESHARED_KEY|g" \
            -e "s|{{ICECAST_SOURCE_PASS}}|$ICECAST_SOURCE_PASS|g" \
            -e "s|{{QBIT_SAVE_PATH}}|$QBIT_SAVE_PATH|g" \
            -e "s|{{NTFY_TOPIC}}|$NTFY_TOPIC|g" \
            -e "s|{{NTFY_TOKEN}}|$NTFY_TOKEN|g" \
            -e "s|{{PROXY_AUTH}}|$PROXY_AUTH|g" \
            -e "s|{{PROXY_USER}}|$PROXY_USER|g" \
            -e "s|{{PROXY_PASS}}|$PROXY_PASS|g" \
            -e "s|{{CROWDSEC_CUSTOMER_ID}}|$CROWDSEC_CUSTOMER_ID|g" \
            -e "s|{{CROWDSEC_API_KEY}}|$CROWDSEC_API_KEY|g" \
            "$1"
    }

    # Docker configs
    echo "   Writing docker configs..."
    sed_fill "$src_dir/docker/.env"
    sed_fill "$src_dir/docker/caddy/Caddyfile"
    sed_fill "$src_dir/docker/synapse/homeserver.yaml"
    sed_fill "$src_dir/docker/gitea/app.ini"
    sed_fill "$src_dir/docker/qbittorrent/qBittorrent.conf"
    sed_fill "$src_dir/docker/ntfy/config/server.yml"

    # Icecast config (conditional)
    if [ "$ENABLE_ICECAST" = "y" ]; then
        echo "   Writing Icecast config..."
        sed_fill "$src_dir/docker/icecast/icecast.xml"
    fi

    # Host configs
    echo "   Writing host configs..."
    cat > "$src_dir/host/wireguard/wg0.conf" <<EOF
# WireGuard Configuration
# Generated by lemon-vps

[Interface]
PrivateKey = $WG_PRIVATE_KEY
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = $WG_CLIENT_PUBLIC_KEY
PresharedKey = $WG_PRESHARED_KEY
AllowedIPs = 10.0.0.2/32
EOF

    # CrowdSec configs (conditional)
    if [ "$ENABLE_CROWDSEC" = "y" ]; then
        echo "   Writing CrowdSec configs..."
        sed_fill "$src_dir/host/crowdsec/config/crowdsec.yaml"
        sed_fill "$src_dir/host/crowdsec/config/acquis.yaml"
    fi

    # Export generated values for later use
    export WG_PRIVATE_KEY WG_PUBLIC_KEY WG_PRESHARED_KEY WG_CLIENT_PRIVATE_KEY MATRIX_SECRET_KEY NTFY_TOKEN

    echo "✅ Configs generated"
}
